### ISSUE TITLE
Convert composite's property map to json object

### ISSUE THREAD

**Issue by refactoriel** [crossplane-contrib/function-shell#38]
# Feature Request

Cool function! I think it would be a good fit for a few of my use cases.

## What problem are you facing?

I'd like to use this function to send off the XR's `spec` to some http endpoint that does some complex validations. I can get the XR's spec via
```yaml
...
        shellEnvVars:
          - key: THESPEC
            valueRef: spec
...
```
but this just prints the go map like `map[foo:bar how:map[can:map[this:map[be:converted to json?]]]]`.

## How could this Function help solve your problem?

Would be great if maps could be transformed to json objects or if the function offered a tool to do it inside the `shellCommand` step.
