### ISSUE TITLE
x86 executable packed into the arm64 image

### ISSUE THREAD

**Issue by stevendborrelli** [crossplane-contrib/function-shell#54]
# Bug Report

The x86 executable is packed into the arm64 image.

## How can we reproduce it?

Run the following shell command on a M-series Mac:

```yaml
  shellCommand: |
          file /usr/local/aws-cli/v2/current/dist/aws
        stdoutField: status.functionShell.r53HostedZone.stdout
        stderrField: status.functionShell.r53HostedZone.stderr
```

The result will be:

```yaml
  functionShell:
      stderr: ""
      stdout: '/usr/local/aws-cli/v2/current/dist/aws: ELF 64-bit LSB executable,
        x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2,
        BuildID[sha1]=8485f6953c06d12b9865185ba3466fdbf9b4a65c, for GNU/Linux 2.6.32,
        stripped'

```

## What environment did it happen in?

Function version:
